### ISSUE TITLE
DFConAgPfSense current build download not clearly documented or easily downloadable 

### ISSUE THREAD

**Issue by PeetMcK** [DynFi/DFConAgPfSense#2]
The project ReadMe  instructs the use of a broken link to install the plugin:

https://dynfi.com/connection-agent/download/pfsense/dfconag-latest-installer.sh instead of https://dynfi.com/files/connection-agent/pfsense/dfconag-latest-installer.sh

The instructions here work: https://dynfi.com/en/articles/dynfi-manager-connection-agent/. However, it's a not easily discovered blog post and not part of the documentation for this [Repo](https://github.com/DynFi/DFConAgPfSense#readme) or the [DynfiManager documentation](https://dynfi.com/documentation/connection-agent.html.). 

Could this the repo readme be updated? Could the documentation be updated? Would it be possible to host the pkg here as a release?

**Comment by oshogbo** [comment]
> Could this the repo readme be updated?

Fixed thank you.

> Could the documentation be updated?
 
We will fix that.

> Would it be possible to host the pkg here as a release?

Yes we will provide it here.
